starlark/example_test.go
...by turning it into a Test and asserting for either of the two valid outcomes.
=> starlark: fix flaky Example of parallel loading

starlark/eval_test.go, starlark/hashtable_test.go, starlark/int.go
Hey, Alan. Thought I'd check out your new toy...in my favorite way, which is peeking a bit at the benchmarks you cared enough to write. :) I'm afraid this PR isn't particularly exciting; happy to abandon some or all of it at your whim. If there's anything you'd like me to take a more serious look at, though, I'd be happy to do so.
=> Minor optimizations

internal/chunkedfile/chunkedfile.go, internal/compile/compile.go, repl/repl.go, starlark/int.go, starlark/library.go, starlark/value.go, syntax/scan.go
=> fix nits found by various static tools

starlark/testdata/dict.star
=> starlark/testdata: fix mistakes in tests

cmd/starlark/starlark.go
-c was chosen to match Python. Sample:
$ starlark -c "print(max(range(10)))"
9
$ starlark -c "a = 'hi'" -showenv
a = "hi"
=> cmd/starlark: add -c flag to execute cmdline program

syntax/parse.go
(introduced in 6be536f)
Also factor similar *args/*kwargs parsing in the same way.
=> syntax: fix bug in parser

doc/spec.md, starlark/eval_test.go, starlark/library.go
...but add a sep=" " parameter.
Updates bazelbuild/starlark#22
=> print: disallow **kwargs

internal/chunkedfile/chunkedfile.go
The test framework adds its own such prefix, confusing editors.
Putting them on separate lines makes it easier to step through.
=> internal/chunkedfile: print newline before file:line:col errors

syntax/scan.go, syntax/testdata/errors.star
=> syntax: improve error message for unmatched close paren

starlark/eval.go, starlark/testdata/string.star
=> starlark: check that interpolation consumes sole non-tuple argument

syntax/quote.go, syntax/testdata/errors.star
=> syntax: parse unicode escape sequences as uints

syntax/scan.go, syntax/scan_test.go
=> syntax: print RBRACE correctly in scan errors

cmd/starlark/starlark.go, starlark/bench_test.go, starlark/eval.go, starlark/example_test.go, starlark/library.go, starlark/value.go
...and remove three ad-hoc implementations.
=> starlark: add StringDict.Keys method

starlark/library.go, starlark/testdata/string.star
=> starlark: disallow {+1} in format strings

syntax/parse.go, syntax/parse_test.go
=> syntax: check for trailing junk in ParseCompoundStmt

cmd/starlark/starlark.go, doc/spec.md, resolve/resolve.go, resolve/resolve_test.go, starlark/eval_test.go, starlark/testdata/int.star, starlark/testdata/set.star, starlark/testdata/string.star
See https://github.com/bazelbuild/starlark/issues/20#issuecomment-456647994
=> resolve: enable bitwise (& | ~ ^ << >>) operators always

starlark/library.go, starlark/testdata/dict.star
=> starlark: dict(None) and dict.update(None) are errors

syntax/scan.go, syntax/scan_test.go
...caused by typo in slice expression.
Also, add missing tokenNames[WHILE].
Fixes #104
=> syntax: fix outdent bug in scanner

starlark/bench_test.go, starlark/testdata/benchmark.star
=> starlark: fix broken benchmark (needed -nesteddef)

starlark/eval.go, starlark/library.go, starlark/value.go, starlarkstruct/struct.go, starlarktest/starlarktest.go, syntax/quote.go, syntax/scan.go
=> all: use strings.Builder

starlark/library.go, starlark/testdata/string.star
...in string.join and several other functions.
+ Test of string.join.
=> starlark: report name of failing function

doc/spec.md, starlark/library.go, starlark/testdata/builtins.star
Updates bazelbuild/starlark#40
=> starlark: make dir return a sorted list

cmd/starlark/starlark.go, starlark/eval.go, starlark/interp.go, starlark/profile.go, starlark/value.go
=> starlark: a simple pprof-compatible execution-time profiler

cmd/starlark/starlark.go
=> cmd/starlark: add Go memory profiling support

starlark/library.go
The earlier change #174 did this only partially.
To make this easier, the nameErr helper adds the "name: " prefix to an error or string.
Also, the signature of builtinMethod has been simplified.
=> starlark: include name of built-in function in errors it returns

starlark/eval_test.go, starlark/library.go, starlark/testdata/builtins.star
=> starlark: improve error message from UnpackArgs

doc/spec.md
=> doc: document string.{,l,r}strip parameter

internal/compile/compile.go
Linear searches through the line-number tables show up as a major
hotspot (>90% CPU) in one application.
In particular, the same handful of functions are called repeatedly.
This change decodes the LNT at most once and retains it,
allowing us to use binary instead of linear search.
sort.Search was inlined to avoid the dynamic dispatch.
In a profile of the above application, using sort.Search reduced
real time to 550ms (down from 3500ms), and Funcode.Position to
5% (down from 90%) of CPU cycles.
Inlining sort.Search further reduced it to 2.7%.
=> internal/compile: optimize Funcode.Position

doc/spec.md
Updates bazelbuild/starlark#47
=> doc: print: drop mention of kwargs

doc/spec.md, starlark/library.go, starlark/testdata/builtins.star, starlarktest/assert.star
Updates bazelbuild/starlark#47
=> starlark: add a fail function

starlark/example_test.go
=> starlark: add example of Starlark built-in function in Go

syntax/scan_test.go
See also bazelbuild/bazel#9210
=> syntax: add some scanner test cases

starlarktest/starlarktest.go
https://github.com/google/starlark-go/issues/250
=> Adding support for Bazel test to use DataFile

go.mod, go.sum
Initialize Go module support.
Close: #232
=> go.mod: init Go module

README.md
Reduce cognitive burden to find documentation link
=> Add godoc documentation badge

starlark/eval_test.go, starlark/unpack.go
Fixes https://github.com/google/starlark-go/issues/267
This bit me recently, so I took the liberty of proposing something very minimalist that borrows from the json package's Unmarshaler
=> Support for type-specific unpack logic

doc/spec.md, resolve/resolve.go, resolve/testdata/resolve.star
This is a potentially breaking language change, but I suspect
few users care. If you are one of them, please report the issue.
Fixes https://github.com/google/starlark-go/issues/275
=> spec: load statements may not be nested in any other statement

starlark/unpack.go
=> starlark: add examples of UnpackArgs

starlarktest/starlarktest.go
=> starlarktest: fix typo in comment

doc/spec.md, resolve/resolve.go, resolve/testdata/resolve.star, starlark/testdata/assign.star
See https://github.com/bazelbuild/starlark/issues/93
=> starlark: permit assigments to () and []

starlark/int_posix64.go
=> fix: mmap failure on linux after the android fix

starlark/eval.go, starlark/library.go, starlark/testdata/string.star
=> Add special case error for slice index, which overflows int

starlark/eval_test.go, starlark/testdata/misc.star, starlark/value.go
See spec change https://github.com/bazelbuild/starlark/issues/116
=> starlark: disallow None < None comparisons

syntax/testdata/scan.star
See https://www.adexchanger.com/data-driven-thinking/no-more-inflammatory-jargon-change-blacklist-to-blocklist/
=> testdata: s/blacklist/blocklist/g per Google policy

starlark/eval_test.go, starlark/unpack.go
Fixes https://github.com/google/starlark-go/issues/347
=> starlark: Add "??" syntax for none-coalescing parameters to UnpackArgs.

README.md
As noted by brandjon@, he implemented Starlark mutability/freezing in 2015.
=> Add François-René Rideau (formerly tunes@google.com) to credits section

starlark/int_generic.go, starlark/int_posix64.go
Signed-off-by: Guoqi Chen <chenguoqi@loongson.cn>
=> starlark: fix tests for loong64.

go.mod, go.sum, internal/test.sh
Also improve failure message of tidiness test.
=> Tidy go.mod file

go.mod, starlark/testdata/function_param.star, starlark/value.go, starlark/value_test.go
=> Added a ParamDefault() method to Function that returns parameter default values.

lib/json/json.go
Before this patch, the json library would log.Fatal() when encoding a
HasAttrs struct whose .Attr(name) return nil or an error for a name that
was previously listed by AttrNames(). Fatal'ing in a library is a bit
presumptuous. In particular, Delve the Go debugger uses go-starlark to
run scripts, and also have implementations of HasAttr that can fail at
runtime (e.g.  a struct modelling a variable from the debugged process
implements Attr uses magic to present the field names of the target
variable in AttrNames, and the Attr implementation returns errors if one
particular field cannot be loaded).
Delve even goes as far as recovering panics from script execution, but
that doesn't work for log.Fatal.
This patch returns the error (thus also failing the script) instead of
the log.Fatal.
=> lib/json: don't fatal on Attr errors when encoding 

starlark/eval.go, starlark/library.go, starlark/value.go
Implement `IN` check for `Tuple` and `*List` via that, too.
Fixes #596 .
=> Add a MembershipCheckable interface and use that for the IN check.

resolve/resolve.go, resolve/testdata/resolve.star
=> [resolve] detect invalid break/continue stmts if inside nested function
