- starlark/value.go
This is a breaking API change.
> skylark: remove (*Dict).Set, use SetKey instead

- internal/compile/compile.go
- starlark/value.go
Also,
- make Opcode.String catch future missing entries.
- document (*Function).Param.
> compile: add missing opcodeName[EXCH]

- cmd/starlark/starlark.go
- doc/spec.md
- starlark/library.go
- starlark/testdata/string.star
Behavior now matches the spec (and Python3).
+ Tests.
Fixes google/skylark#140
> starlark: fix bugs in str.{title,capitalize}

- starlark/interp.go
- starlark/library.go
- starlark/testdata/list.star
- starlark/value.go
The notion of "structural" vs "nonstructural" updates was apparently
never more than a vague idea and was never implemented in Bazel.
Fixes google/skylark#141
> starlark: disallow list element update during iteration over list

- README.md
It's more helpful (and expected) to link the badge to the build status page,
rather than it just being a link to the [badge SVG itself](https://travis-ci.org/google/starlark-go.svg).
> README: link Travis CI badge to build status page

- README.md
`go get` already does the work done by `go install` ¹, so doing a `go install`
afterwards is redundant. Use this property to make the installation
process simpler.
¹ https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies
This assumes a GOPATH workspace mode, but the current directions seem to imply that (i.e., `$GOPATH/bin` is mentioned in the comment).
You may want to include `-u` flag by default, if you'd rather have the `go get` command produce more predictable results. Without `-u`, if the user happens to have really old versions of some dependencies (rather not have them at all), `go get` will not update them and your program may not build. If the user doesn't have those dependencies, `go get` will fetch the latest version. Using the `-u` flag makes `go get -u` …
> README: simplify installation instructions

- resolve/testdata/resolve.star
- starlark/eval_test.go
- starlark/testdata/assign.star
- starlark/testdata/function.star
- starlark/testdata/misc.star
- syntax/parse_test.go
- syntax/scan_test.go
GitHub allows individual issues to be transferred but provides no bulk
mechanism---also, we've started reusing issue numbers---so I
transferred the few open issues and left the closed ones.
> all: use explicit URLs to refer to old Starlark issues

- starlark/eval.go
- starlark/testdata/function.star
> starlark: reject dup keyword args in call to func with **kwargs param

- resolve/resolve.go
- resolve/testdata/resolve.star
This change causes the AllowGlobalReassign flag (used for legacy Bazel
semantics) to also allow use of predeclared names prior to a global
binding of the same name, as in:
print(len); len=1; print(len)
This effectively reverses github.com/google/skylark/pull/123 behind an option.
See github.com/google/skylark/issues/116 for discussion.
> resolve: allow use of predeclared name prior to a global def (if AllowGlobalReassign)

- starlark/eval.go
- starlark/testdata/string.star
- starlark/testdata/tuple.star
We limit repeats arbitrarily to 10,000,000 elements
to avoid accidental OOM. It's still possible to
OOM piecewise but we can't fix that.
Also, handle integer overflow in multiplication
and excessive repeats counts.
> starlark: fix overflow in repeat operator

- internal/compile/compile.go
- starlark/testdata/assign.star
This change fixes the Go implementation of starlark vis-a-vis parens on the LHS of augmented assignments. Fixing the spec is tracked at https://github.com/bazelbuild/bazel/issues/6756.
cc @laurentlb
Fixes #25
> starlark: allow parenthesized expressions on LHS of augmented assignments

- starlark/hashtable_test.go
- starlark/int.go
Fix a typo in int.go.
Re-work the hashtable test to use a global.
Sorry for the make-work.
I guess I''ll try to do things the GitHub way from now on, which means using an entire branch to work on a single commit. (How are you even supposed to work on multiple dependent changes using PRs? Or maintain clean, atomic commits in the face of pressure to the contrary? GitHub has managed to squander git's flagship feature, cheap branches.)
> starlark: address code review comments from #23

- internal/compile/compile.go
- internal/compile/serial.go
- starlark/bench_test.go
- starlark/eval.go
- starlark/eval_test.go
- starlark/testdata/paths.bzl
The gob encoding was showing up in profiles.
This change replaces it with a simple hand-written binary encoding
using strings and varints.  Strings and byte slices are allocated
in one contiguous block to reduce allocations.
The new encoder and decoder are about 5x faster with 10x fewer allocs.
+ benchmark
> internal/compile: optimize the encoding

- internal/compile/compile.go
- internal/compile/serial.go
- starlark/eval_test.go
- starlark/value.go
If the first statement of the body of a function is a string its value
will be returned when calling the Doc() method of starlark.(*Function).
Implements #35
> Support doc strings

- doc/spec.md
- starlark/eval.go
- starlark/testdata/dict.star
This feature (which Python does not have) has been deprecated for a long time.
> starlark: drop support for dict+dict

- starlark/eval.go
...when printing a frame or backtrace.
This is more of a low-risk usability hack than a specified feature at
this point. I don't think it warrants a (breaking) change to the
Callable interface.
> starlark: if a built-in Callable defines Position method, use it

- starlark/eval.go
Instead of O(n) appends, using doubling copies.
> Optimize repeat

- doc/spec.md
The Java impl now supports it too.
> doc: remove implementation note at dict.clear

- starlark/library.go
- starlark/testdata/dict.star
> starlark: check for duplicate kwarg keys in dict

- internal/compile/compile.go
- starlark/eval_test.go
- starlark/testdata/recursion.star
```
make break and continue work with while
break and continue should work inside a while loop instead of causing a
compiler panic.
```
> make break and continue work with while

- doc/spec.md
- resolve/resolve.go
- resolve/testdata/resolve.star
- starlark/testdata/dict.star
- starlark/testdata/function.star
This complements the dynamic checks, which is already implemented
in setArgs and in UnpackeArgs.
Updates bazelbuild/starlark#21
> resolve: statically reject duplicate keyword args in a call

- cmd/starlark/starlark.go
- internal/compile/codegen_test.go
- internal/compile/compile.go
- repl/repl.go
- starlark/debug.go
- starlark/eval.go
- starlark/eval_test.go
- starlark/example_test.go
- starlark/interp.go
This change adds a number of small features to improve debugging.
The actual debugger API will come in a later change.
- Thread.Name : an optional string field that describes the purpose of
the thread, for use in debugging.
- (*Program).Filename: a method that reports the file of the program.
Also, a String method that returns the same thing.
Also, a test that it reports the correct location even for
an empty file (a special case of the previous implementation).
- (*Frame).Local(i int): a method to return the value of a local
variable of an active frame, such as one might use in debugger's
stack trace.
- ExprFunc: creates a starlark.Function from a given expression,
such as one might use in a debugger REPL.
> starlark: API additions for improved debugging

- cmd/starlark/starlark.go
- doc/spec.md
- resolve/resolve.go
- resolve/resolve_test.go
- resolve/testdata/resolve.star
- starlark/eval_test.go
- starlark/testdata/assign.star
- starlark/testdata/bool.star
- starlark/testdata/builtins.star
- starlark/testdata/dict.star
- starlark/testdata/float.star
- starlark/testdata/function.star
- starlark/testdata/int.star
- starlark/testdata/list.star
- starlark/testdata/misc.star
- starlark/testdata/set.star
- starlark/testdata/string.star
Also:
- make the option handling work the same across all tests
- be explicit about which options are needed in each test chunk
- improve documentation of options
- rename fp option to float consistently
- rename global_reassign option to globalreassign consistently
> starlark: permit if/for/while at toplevel if -globalreassign

- internal/compile/compile.go
- starlark/eval.go
- starlark/int.go
- starlark/value.go
This mirrors the treatment of HasBinary.
> starlark: HasUnary: allow extension types to define +x, -x, ~x

- starlark/eval.go
This allows clients to synthesize stack frames for non-Starlark (e.g. Go) function calls.
(See wip-stargo branch.)
> starlark: expose NewFrame operation

- starlark/eval_test.go
- starlark/library.go
When computing the error message, the parameter's Type method is
called. Mostly this works, but it may panic for a user-defined
type whose Type method doesn't work on the zero value.
Recover from the panic and show the Go type instead.
+ Test
> starlark: fix a crash in UnpackArgs

- starlark/interp.go
- starlark/library.go
- starlark/value.go
Allow:
- f(**IterableMapping)
- dict(x, IterableMapping)
- dict.update(IterableMapping)
(Intended for use by go.map in stargo.)
> starlark: add IterableMapping, abstraction of *Dict

- starlark/eval_test.go
- starlark/testdata/module.star
- starlarkstruct/module.go
- starlarkstruct/struct.go
- starlarktest/assert.star
- starlarktest/starlarktest.go
...instead of struct, which is more suited to dynamic values.
This type will be used for Stargo (see wip-stargo branch).
For example, this load statement
load("go", http="net/http", json="encoding/json")
would load two modules.
Aside: Starlark's load statement is arguably its weakest feature.
Python and Go both have an 'import' statement that loads a collection
of names at once, such as "import os"; later uses are qualified, such
as os.mkdir. This is what we want for assert, for Stargo, and often in
Bazel, where it is tedious to enumerate every name when importing a
module with a broad API. There is room for improvement in the spec.
> starlark: add 'module' type, and use it for assert module

- repl/repl.go
- starlark/eval.go
- syntax/parse.go
- syntax/parse_test.go
- syntax/scan.go
- syntax/scan_test.go
- syntax/testdata/errors.star
Previously, the REPL used a heuristic: it would consume a single line
and attempt to parse it; if that failed, it would consume lines up to
a blank line then parse the whole as a file. This was suboptimal for
various reasons: it failed to parse lines ending with an unfinished
multi-line string literal, for example, and it would prematurely
stop reading even while parentheses were open.
This change integrates the REPL with the scanner and parser (as Python
does). The REPL invokes a new parser entry point, ParseCompoundStmt,
that consumes only enough input to parse a compound statement, defined
as (a) blank line, (b) a semicolon-separated list of simple statements
all on one line, or (c) a complex statement such as def, if or for.
If the 'src' value provided to the scanner is a function of …
> syntax: improve REPL parsing

- doc/spec.md
```
doc: close bold tag
Everything after the implementation note of the "If statements" section
was accidentally bolded.
```
> doc: close bold tag

- syntax/scan.go
- syntax/scan_test.go
'~' is not like the operators that accept a following '='.
Fixes #107
> syntax: fix bug scanning ~=

- starlark/library.go
- starlark/testdata/int.star
The int function has been simplified, at the cost of an extra memory
allocation for negative numbers.
Fixes #108
> starlark: fix parsing of int('0Oxa', 8)

- starlark/library.go
- starlark/testdata/int.star
The implementation of the int built-in explicitly handles signs
and then strips them. It then passes the remaining string to math/big.
However, math/big also accepts and handles signs. This led to
int("--4") returning 4 (somewhat correctly), and to
int("0x-4", 16) returning -4 (again, somewhat correctly).
Since we are handling sign explicitly, check for and complain about
signs in strings we are about to pass in to math/big.
Follow-up to #108 and #109.
> starlark: reject double-signs and misplaced signs in int

- starlark/library.go
- starlark/testdata/builtins.star
- starlark/value.go
The range_ constructor correctly calculated a len of 0 when constructing
an empty range, but slicing a range did not; it calculated a len of 1.
This change unifies the length calculation.
This allow us to simplify range construction along the way.
Fixes #116
> starlark: correctly calculate len when slicing an empty range

- doc/spec.md
- internal/compile/compile.go
..now that the spec is resolved.
> doc: document call argument evaluation order

- doc/spec.md
- resolve/resolve.go
- resolve/testdata/resolve.star
- starlark/testdata/assign.star
...unless -globalreassign is set.
Formerly, the Go implementation permitted x+=y on the basis
that we couldn't statically tell whether x was a list (in which
case x+=y means x.extend(y), which is not a rebinding), or some
other type, in which case it is a forbidden rebinding.
This change makes it match the Java implementation.
See https://github.com/bazelbuild/starlark/issues/20#issuecomment-456647994
Most non-Bazel-like clients of Starlark set the -globalreassign flag.
> resolve: disallow augmented assignments at toplevel

- doc/spec.md
- starlark/eval.go
- starlark/library.go
- starlark/testdata/builtins.star
- starlark/testdata/list.star
Also, improve out-of-range error messages.
Fixes #119
> starlark: permit list.pop(i) for -n <= i < 0

- starlark/eval.go
- starlark/interp.go
- merge two functions that were separate for no good reason
- remove low-value log statement and 'debug' constant
> starlark: minor cleanup in (*Function).CallInternal

- starlarkstruct/struct.go
- starlarkstruct/testdata/struct.star
These methods are a (mis)feature of Bazel and don't belong here.
> starlarkstruct: remove to_json/to_proto methods

- internal/spell/spell.go
- resolve/resolve.go
- resolve/testdata/resolve.star
- starlark/eval.go
- starlark/eval_test.go
- starlark/testdata/module.star
- starlark/value.go
- starlarkstruct/struct.go
Move spell.go to internal/spell package to enable re-use.
Unfortunately the resolver API provides no way for it to enumerate
predeclared and universe, so these candidates are missing.
> resolve: report likely identifier misspelling

- doc/spec.md
- starlark/library.go
- starlark/testdata/bool.star
Previously they would accept any value and use it truth-value.
Python permits any bool or int, more by historical accident than design.
This change may cause existing programs to have dynamic errors!
Updates bazelbuild/starlark#30
> starlark: make built-ins require True/False for bool params

- doc/spec.md
- starlark/library.go
- starlark/testdata/bool.star
- starlark/testdata/string.star
Unlike split, splitlines may return an empty list.
Fixes #147
> starlark: fix bug: ''.splitlines() is special case

- doc/spec.md
- internal/compile/compile.go
- internal/compile/serial.go
- resolve/resolve.go
- resolve/testdata/resolve.star
- starlark/eval.go
- starlark/eval_test.go
- starlark/value.go
- syntax/grammar.txt
- syntax/parse.go
- syntax/parse_test.go
- syntax/syntax.go
- syntax/testdata/errors.star
Following a hitherto undocumented feature of Skylark-in-Java,
which in turn follows Python3,
a function declaration may now include optional parameters
after the *args parameter:
```
def f(a, b, c=1, *args, d=2, **kwargs)
```
The parameter d is a "keyword-only" parameter as it can
never by assigned from a positional parameter; all positional
arguments surplus to a, b, and c are put in a tuple and
assigned to args.
To declare a non-variadic function with keyword-only arguments,
the *args parameter is replaced by just *:
```
def f(a, b, c=1, *, d=2, **kwargs)
```
The * parameter is not a real parameter; it just serves as a
separator between the parameter that may be specified positionally
and the keyword-only ones.
Spec proposal at bazelbuild/starlark#23
Fixes #61
> Support keyword-only function parameters

- doc/spec.md
- internal/compile/compile.go
- resolve/resolve.go
- resolve/testdata/resolve.star
- starlark/eval.go
- starlark/eval_test.go
- starlark/interp.go
- starlark/testdata/function.star
In def f(a, b=1, *, d, e=2, f), the parameters d and f
are keyword-only (because they come after the * or *args parameter),
but have no default value, so they are mandatory.
Also:
- improve the error messages
- spec update
- avoid need for "defined" bitset in setArgs
Updates bazelbuild/starlark#23
> Support required keyword-only parameters

- syntax/parse_test.go
- syntax/syntax.go
- syntax/walk.go
- syntax/walk_test.go
In "def f(*, x)", the unary expression has no operand.
Document this and be appropriately defensive.
Add test (and example) of walk.
Fixes #157
> syntax: handle UnaryExpr{Op:STAR, X:nil}

- starlark/eval.go
- starlark/int.go
- starlark/int_test.go
- starlark/library.go
- starlark/testdata/benchmark.star
- starlark/testdata/int.star
Represents small ints as int64 values promoting to big.Int types when needed. Have added some simple benchmarking. Based off of https://github.com/robpike/ivy int/bigint types.
```
Benchmark/bench_bigint-8                   10000            187182 ns/op
Benchmark/bench_int-8                      10000            180208 ns/op
Benchmark/bench_bigint-8                    5000            261473 ns/op
Benchmark/bench_int-8                      10000            128741 ns/op
```
> Small int as int64

- .travis.yml
Now that 1.12 is out, 1.10 is the minimum supported version.
> travis: bump to Go version 1.10

- starlark/value.go
In PR #86, we considered multiple APIs for writeValue.
We settled on passing a nil path, but the doc comment
missed that. Fix it now.
> starlark: correct writeValue docs

- internal/compile/compile.go
- internal/compile/serial.go
- resolve/resolve.go
- starlark/eval.go
- syntax/binding.go
- syntax/syntax.go
This refactoring exposes the concept of Binding, which was previously
internal to the resolver. Previously the Scope and Index fields of the
binding were copied into each Ident; now the relationship is indirect.
A Binding is the entity created by the first binding occurrence of a
name, and the binding ties together all uses of that name.
This change is a preparation for fixing issue #170, which requires
that we mark the bindings that need to be allocated indirectly in
closure cells. Currently, in the absence of an indirect relationship
there is no way to mark a binding so that all Idents are affected.
This change leads to some a minor simplification in lookupLexical,
which used to synthesize a new Ident, when logically it is creating
only a new binding.
Unfortunately, Binding and Scope …
> syntax: expose Binding concept

- internal/compile/compile.go
- internal/compile/serial.go
- resolve/resolve.go
- starlark/eval_test.go
- starlark/interp.go
- starlark/testdata/assign.star
- starlark/testdata/function.star
- syntax/binding.go
- syntax/syntax.go
This change causes closures for nested functions to capture their
enclosing functions' variables by reference. Even though an inner
function cannot update outer variables, it must observe updates to
them made by the outer function.
A special case of this is a nested recursive function f:
def outer():
def f(): ...f()...
The def f statement constructs a closure which captures f, and then
binds the closure value to f. If the closure captures by value (as
before this change), the def statement will fail because f is
undefined (see issue #170). Now, the closure captures a reference
to f, so it is safe to execute before f has been assigned.
This is implemented as follows. During resolving, captured local
variables such as f are marked as as "cells". The compiler assumes and
guarantees that such …
> starlark: capture free variables by reference

- internal/compile/compile.go
- resolve/resolve.go
- syntax/binding.go
This restores the nice syntax prior to the refactoring.
> resolve: add aliases for Binding and Scope

- starlark/hashtable.go
- starlark/value.go
Hashtable growth keeps showing up in my profiling.
Preallocating the table when the size is known makes it much faster.
The NewDict function lets API clients control this.
Also NewSet.
> starlark: NewDict(n) creates a dict with space for n elements

- doc/spec.md
- internal/compile/compile.go
- resolve/resolve.go
- resolve/resolve_test.go
- resolve/testdata/resolve.star
- starlark/eval_test.go
- starlark/testdata/assign.star
- syntax/binding.go
Previously, load statements created global bindings.
As an often-unwanted consequence, names loaded by one module
would leak into its module dictionary and be visible to others.
This change to the resolver makes load define file-local variables
using a similar approach to Go: a new lexical block (the file block)
between function/comprehension blocks and the globals.
The set of names in the file block and the globals must be disjoint.
This incompatible change is guarded by the LoadBindsGlobally flag,
which is false by default. Users who want the old behavior may set
it to true, but they should prepare for it to go away entirely.
After that point, the old behavior may be simulated thus:
- load("...", "x")
+ load("...", _x="x"); x = _x # re-export
> resolve: load statements now create local bindings

- starlark/eval.go
- starlark/eval_test.go
- starlark/interp.go
- syntax/scan.go
Previously, only errors originating in Starlark code would be
represented as EvalErr. The backtrace would include frames for
built-in functions that the exception passed through, but not
for the originating frame.
Also, report `<builtin>` not `<builtin>:1` for the position
of such frames. Position.Line==0 no longer implies !IsValid.
Added test of errors originating in a built-in frame.
> starlark: return EvalErr for errors originating in built-ins

- starlark/profile.go
- starlark/profile_test.go
Also, add integration test of profiler and 'go tool pprof'.
> starlark/profile: use real time (not monotonic) clock for Profile.time

- starlark/debug.go
- starlark/eval.go
- starlark/eval_test.go
- starlark/interp.go
- starlark/profile.go
- starlarktest/starlarktest.go
Prior to this CL, the interpreter stack was implemented as
a "spaghetti stack", a linked tree of Frames. This meant
that EvalError (for example) could make a copy of the stack
just by retaining a *Frame reference at its moment of creation,
but this forced every Starlark call to allocate a new Frame.
Also, in non-error cases (e.g. application built-ins that retain the
call stack), the retained references (linked lists of frames) were
pointers to Frames that were actively mutated by ongoing execution.
This change separates the internal and external data types for Frames.
Internal frames (type Frame) are still, for now, linked trees, but
the Frame type is deprecated and will soon be made private.
It may still be accessed through an interface, DebugFrame, for the
very few clients that need …
> starlark: new CallStack API (and Frame deprecation)

- starlark/debug.go
- starlark/eval.go
- starlark/interp.go
Also, an optimization: use the slack portion of the
Thread.stack slice as a free-list of frames, to avoid
allocating a frame on most calls.
THIS IS A BREAKING API CHANGE.
It will be submitted on May 6.
Clients: please switch to the new CallStack API before then.
> starlark: remove deprecated Frame type

- doc/spec.md
- starlark/library.go
- starlark/testdata/float.star
- starlark/testdata/function.star
- starlark/testdata/string.star
- starlark/value.go
Previously, hash would allow any operand defined as hashable
by the spec, and would use (for strings at least) a fast
hardware implementation that varies across process restarts.
+ Test.
> hash: allow only strings, and use a deterministic algorithm

- internal/compile/codegen_test.go
- internal/compile/compile.go
- starlark/eval.go
- starlark/interp.go
- starlark/value.go
The function knows where to split it.
Also, refactor the common parts of all Functions in the same module---
program, predeclared, globals, constants---into a separate data structure,
module. This reduces the size of Function from 14 words to 8.
> internal/compile: opt: emit a combined tuple for defaults + freevars

- doc/spec.md
- syntax/scan.go
- syntax/scan_test.go
Use 0o644 instead.
See also https://github.com/bazelbuild/bazel/issues/8059
> syntax: drop legacy (0644) octal literals

- internal/compile/compile.go
- internal/compile/compile_test.go
- starlark/eval_test.go
Prior to this CL, the line-number table in the compiled code
recorded only the line number for each program counter value.
This change causes it to record columns too.
By stealing bits from the PC and line fields, we can encode the
additional information in the same 16 bits of space, again using
the same delta encoding approach for columns.
The field widths (uint4 for Δpc, int5 for Δline, and int6 for Δcol)
were chosen after analysis of a large set of files to minimize
the frequency of overflows, which are more common now but still
account for only about 2.5% of all rows.
The decompressed LNTs are 50% bigger, but only a minority
of functions' LNTs are materialized in a typical program
due to calls to Funcode.Position via Thread.CallStack.
Fixes #176
> internal/compile: record column information for each PC offset

- doc/spec.md
Since each of octal_lit, hex_lit and binary_lit
specify a mandatory prefix (e.g. 0o, 0x and 0b),
we extend decimal_lit to allow for the decimal
literal zero.
> spec: add '0' as valid decimal_lit

- repl/repl.go
PR #178 made them local to the file, but each statement in the REPL is
its own "file". This change sets (and restores) the flag for the
legacy behavior in the REPL.
This change is more workaround than fix, as it is not safe w.r.t.
concurrent interpreters, but we already have problems of that kind.
Perhaps we need to plumb options more thoroughly instead of using
globals.
Updates #224
> repl: treat load bindings as global in the REPL

- doc/spec.md
`not` is not a binary operator and shouldn't be mentioned in their precedence order.
> Remove `not` from binary operators in the spec

- starlark/value.go
...to avoid its abuse to access non-parameter locals.
> starlark: assert precondition of Function.Param

- internal/compile/compile.go
- resolve/resolve.go
- starlark/eval.go
I've replaced some calls to `log.Fatal` and `log.Fatalf` with panics. I believe those are all unreachable internal errors (in practice) so this is a somewhat inconsequential nitpick; however if this code were ever to execute, I believe a recoverable panic, carrying stacktrace information is preferrable to getting the calling process instantly killed.
> starlark,resolve,internal/compile: replace log.Fatal with panic

- doc/spec.md
The ToC links to #value-concepts, but the actual anchor being generated was #value-concepts-value-concepts.
I changed the anchor, but let me know if you'd rather I changed the ToC link
> spec: fix a broken link

- starlark/eval.go
- starlark/eval_test.go
- starlark/interp.go
The errors from a load() were dropping the stack trace on the floor. Hopefully this should be non-controversial.
I also considered using the Go 1.13 error wrapping API, but decided that there are probably too many starlark users on Go 1.12
> starlark: preserve the backtrace in load() errors

- repl/repl.go
- resolve/resolve.go
- starlark/eval.go
- starlark/eval_test.go
Previously, in the REPL, the globals bound by one chunk would become
the "predeclared" bindings of the next chunk. However, this produced
the wrong result for [x = x + 1] because both occurrences of x would
resolve to the same global x, which was undefined when the right-hand
side expression was evaluated, leading to a dynamic error. It would
fail for [x += 1] for a similar reason.
This change extends the resolver to allow clients to provide it with a
non-empty set of module globals. Thus the globals of one chunk remain
the globals of the next chunk, and the predeclared set is always empty.
The new API functions are intended for use only by the REPL.
Fixes #233
> resolve: retain globals across REPL chunks

- .travis.yml
Removed "sudo: false". It has no effect.
Added explicit test script.
* 'go test -mod=readonly ./...' will report an error if go.mod or
go.sum is incomplete, since no requirements may be added with
-mod=readonly.
* The rest of the script checks that go.mod and go.sum do not change
after running 'go mod tidy'. This verifies that there are no
redundant requirements or sums to remove.
Changed minimum Go version to 1.11.x. This is the oldest version
with support for modules. Older versions will still work in GOPATH
mode, but versions lower than 1.12 are unsupported by the Go, so
there's little point in adding additional test code for them.
> .travis.yml: test that module is tidy

- .travis.yml
The current setup only runs tests with Go 1.11.x and the latest source
code on the `master` branch, but is not running the more recent releases
1.12.x and 1.13.x which may be widely in use. This change includes both
of those versions as well.
> Also run tests with Go 1.12.x and 1.13.x

- syntax/scan.go
* `return nil, err` after assigning to `err` (rather than ignoring it)
* removed initialization of a variable just before it's re-assigned
Both of these issues were found in the Go Repord Card:
https://goreportcard.com/report/github.com/google/starlark-go#ineffassign
> Fix ineffective assignments

- README.md
Travis CI is more of a status badge, not an aspect of documentation, and
is often kept at the top of the project's README, together with other
badges, such as Go Report Card, etc., which don't belong in the
"documentation" section.
> Move Travis CI badge to the top of file [skip ci]

- doc/spec.md
- starlark/testdata/function.star
- syntax/grammar.txt
- syntax/parse.go
- syntax/testdata/errors.star
Following Python3 and Starlark-in-Java, this change causes
the parser not to reject a trailing comma, even after *args or **kwargs,
in function definitions and function calls.
Fixes #256
> syntax: permit trailing commas in all function defs and calls

- starlark/library.go
- starlark/value.go
NewBuiltin and Sort are called at init. Slightly faster method calls:
```
benchmark                            old ns/op     new ns/op     delta
BenchmarkStringHash/hard-1-8         3.90          3.65          -6.41%
BenchmarkStringHash/soft-1-8         2.69          2.21          -17.84%
BenchmarkStringHash/hard-2-8         4.52          4.38          -3.10%
BenchmarkStringHash/soft-2-8         3.55          2.68          -24.51%
BenchmarkStringHash/hard-4-8         5.32          5.07          -4.70%
BenchmarkStringHash/soft-4-8         5.32          3.63          -31.77%
BenchmarkStringHash/hard-8-8         7.58          7.03          -7.26%
BenchmarkStringHash/soft-8-8         6.62          5.60          -15.41%
BenchmarkStringHash/hard-16-8        7.00          6.43          -8.14% …
```
> starlark: built-in types map of *Builtin

- syntax/scan.go
- syntax/scan_test.go
Prior to this change, the REPL incorrectly scanned
regular and raw string literals containing newlines
because scanString falsely assumed that only
triple-quoted strings can span lines.
```
>>> 'a\
... b'
<stdin>:1:2: string literal has invalid quotes
>>> r'a
... b'
<stdin>:1:2: string literal has invalid quotes
```
Now it does the right thing:
```
>>> 'a\
... b'
"ab"
>>> r'a\
... b'
"a\\\nb"
```
> syntax: fix scanString bug affecting REPL

- starlark/library.go
The stringintconv checker added in
https://go-review.googlesource.com/c/tools/+/235797
requires an explicit rune type for the operand of a string(int) conversion.
> starlark: work around vet false positive

- cmd/starlark/starlark.go
- starlark/eval_test.go
- starlark/testdata/json.star
- starlarkjson/json.go
This is a sketch of a standard module for JSON encoding/decoding for Starlark.
It is intended to subsume, generalize, and eventually
replace the ill-conceived struct.to_json method.
See related issues:
https://github.com/bazelbuild/bazel/issues/7896
https://b/23962735 (Googlers only)
https://b/70210417 (Googlers only)
https://github.com/bazelbuild/bazel/issues/7879#issuecomment-477713954
https://github.com/bazelbuild/bazel/issues/5542
> starlarkjson: a standard json module for Starlark

- starlark/interp.go
This saves 22% of CPU cycles on one call-intensive benchmark.
> Avoid defensive copy in CALL operator when callee is a Starlark function

- starlark/eval.go
- starlark/int_generic.go
- starlark/testdata/string.star
- starlark/testdata/tuple.star
The recent int change didn't compile on 386. Fixed.
Thanks to user @anyktx for pointing this out.
Also, tests of string * int and tuple * int printed a bad
error message containing an integer overflow. Now fixed.
> starlark: fix tests for 386

- starlark/int_generic.go
- starlark/int_posix64.go
> starlark: disable int optimization in iOS, which doesn't support mmap

- starlark/int_posix64.go
Fix https://github.com/google/starlark-go/issues/290#issuecomment-660674313
> fix: `mmap: bad file descriptor` on android arm64

- doc/spec.md
- first loop operand is resolved in enclosing environment
- all loop vars are bound before any expression is resolved
See https://github.com/bazelbuild/starlark/issues/84
> spec: clarify scope rules for comprehensions

- cmd/starlark/starlark.go
- go.mod
- go.sum
- resolve/resolve.go
- resolve/resolve_test.go
- resolve/testdata/resolve.star
- starlark/eval.go
- starlark/eval_test.go
- starlark/int.go
- starlark/library.go
- starlark/testdata/assign.star
- starlark/testdata/bool.star
- starlark/testdata/builtins.star
- starlark/testdata/float.star
- starlark/testdata/int.star
- starlark/testdata/json.star
- starlark/testdata/misc.star
- starlark/testdata/string.star
- starlark/value.go
- starlarkstruct/struct_test.go
This change makes go.starlark.net's floating-point implementation
match the proposed spec (see https://github.com/bazelbuild/starlark/pull/119),
and thus much more closely match the behavior of the Java implementation.
The major changes are:
- Float values are totally ordered; NaN compares greater than +Inf.
- The string form of a finite float value always contains an exponent
or a decimal point, so they are self-evidently not int values.
- Operations that would cause a large integer to become rounded to
an infinite float are now an error.
The resolve.AllowFloat boolean, and the corresponding -float command-line
flag, now have no effect. Floating point support is always enabled.
> starlark: bring floating-point into spec compliance

- resolve/resolve.go
- resolve/testdata/resolve.star
- starlark/eval_test.go
- starlark/testdata/function.star
f(*args, k=v) is a now an error. Use f(k=v, *args).
Arguments are evaluated left-to-right, as in Python2 (but not Python3).
See https://github.com/bazelbuild/starlark/issues/13 for spec change.
This is a breaking language change---but the fix is easy.
> starlark: disallow keyword argument after *args

- starlark/testdata/json.star
- starlarkjson/json.go
This is for consistency with the java.starlark.net implementation
and proposed spec.
This is a (minor) incompatible behavior change.
> starlarkjson: sort dict keys

- starlark/eval.go
- starlark/eval_test.go
Instead, the name of the built-in function is append to the
error message ("Error in foo: ...").
Arguably, the convention of requiring EvalError messages
to start with the name of the function was a mistake, since
it's easy to forget, and easier to move the responsibility
to the stack trace printing logic, as we do here.
> starlark: skip last frame of stack backtrace if built-in

- go.mod
- starlark/eval_test.go
- starlark/int_posix64.go
Also, add test to ensure that new dependencies (such as golang.org/x/sys/unix)
are not added casually.
Fixes #320
> starlark: use portable syscall wrapper for mmap

- starlark/bench_test.go
- starlark/testdata/benchmark.star
The parameter is a wrapper around a testing.B, that provides the
number of iterations and start/stop/reset methods. It follows
the design used in java.starlark.net; see
https://github.com/bazelbuild/starlark/pull/75#pullrequestreview-275604129
https://github.com/bazelbuild/bazel/commit/146cd2cecae52ebad6664046fd1430c2a23b55e1
> starlark: add parameter to bench_xyz(b) benchmark functions

- .travis.yml
Also drops testing against go 1.12.x
It might be worth adding support for Github Actions down the road to reduce the chance of a missed "check" on PRs in the future.
For now, testing with a recent go version would be nice.
> ci: Add support for go 1.15.x to .travis.yml

- starlark/eval_test.go
- starlark/int.go
- starlark/library.go
- starlark/testdata/builtins.star
- starlark/unpack.go
Also, use it in Unpack* functions.
This is a minor breaking change: any call that assumed values
unpacked to 'int' were always in the int32 range will need to be modified
to handle possible int64 values.
> starlark: add ToInt helper function for unpacking values to Go ints

- starlark/eval_test.go
...so that they compile on 32-bit platforms like GOARCH=386.
> starlark: avoid constants > 1<<32 in tests

- starlark/int.go
- starlark/int_test.go
The interface of Int assumes the value is immutable but a reference to
its content is leaked through the BigInt() method, which is mutable.
This fix resolves the leak by:
- making a copy of the *big.Int in MakeBigInt()
- returning a copy of the *big.Int content in BigInt()
- creating an internal method bigInt() for internal use that still
returns reference to the internal big.Int
Fixes: #332
> Fix: Immutability of Int is broken by BigInt method (#332)

- starlark/unpack.go
The UnpackArgs command does not support parsing floats out of arguments. This pull request adds that functionality to the unpackOneArg function which then adds that functionality to the UnpackArgs command.
> Add functionality for parsing floats

- doc/spec.md
See https://github.com/bazelbuild/starlark/issues/148
for change to Starlark spec.
Updates https://github.com/bazelbuild/starlark/issues/148
> doc/spec.md: fix mistake regarding sign of x % y

- cmd/starlark/starlark.go
- doc/spec.md
- resolve/resolve.go
- resolve/resolve_test.go
- resolve/testdata/resolve.star
- starlark/eval_test.go
- starlark/testdata/assign.star
- starlark/testdata/benchmark.star
- starlark/testdata/dict.star
- starlark/testdata/function.star
- starlark/testdata/list.star
- starlarkstruct/struct_test.go
See https://github.com/bazelbuild/starlark/pull/145
for spec changes.
Updates https://github.com/bazelbuild/starlark/issues/20
> resolver: make -nesteddef and -lambda always on

- internal/compile/compile.go
- starlark/interp.go
- starlark/testdata/function.star
The contents of a cell may be null, just like any other local.
We should report this as an error.
So that we can name the variable in the error message,
we change the instruction set so that `LOCAL<local>+CELL`
are combined into a single `LOCALCELL<local>` instruction,
and `FREE<free>+CELL` become a single `FREECELL<free>` instruction.
For symmetry we also combine `LOCAL<local>+SETCELL` into `SETLOCALCELL`,
though it cannot fail. (Happily, all three changes are optimizations
previously described by TODO comments.)
Fixes #340
> starlark: report "uninitialized cell" errors gracefully

- doc/spec.md
- starlark/library.go
- starlark/testdata/int.star
- syntax/syntax.go
Previously, when int was called with an explicit base,
it would report an error if the digit string starts
with a base prefix for a different base, such as int("0b101", 16).
Now, it uses the base prefix only if it matches the requested
base, so the example above would return 0x0b101, as would
int("0x0b101", 16).
The int(string, int) case has been split out for clarity.
Update doc.
Fixes #337
> starlark: fix bug in int(string, base=int)

- starlark/example_test.go
A Thread is created before the outermost `load` and is then never used. (In `load`, a thread is created for each module being loaded.)
> Remove an unused Thread in the sequential load example

- syntax/parse.go
- syntax/parse_test.go
- syntax/scan.go
The new FilePortion type, which may be provided to the scanner,
parser, or ExecFile functions, combines a piece of text
with its start line/column numbers, for applications that
extract a Starlark expression from the middle of a larger file.
Fixes https://github.com/google/starlark-go/issues/346
> syntax: support setting initial line/col for scanner

- lib/time/time.go
- starlark/testdata/time.star
fixes #364 
For many real life use cases, it is important to be a able to support timestamps expressed in nanoseconds.
* Overloads the function `from_timestamp` to be able to set nanoseconds.
* Fixes the documentation of the built in function `from_timestamp` 
* Improves the documentation (not related to this issue)
* Adds a test for the function `now` since it was not covered by any tests (not related to this issue)
> Add support of timestamps in nanoseconds

- doc/spec.md
- lib/math/math.go
- starlark/library.go
- starlark/testdata/builtins.star
- starlark/testdata/math.star
I get two failures that I could not figure out myself. Ideas?
```
--- FAIL: TestExecFile (0.14s)
starlarktest.go:117: Traceback (most recent call last):
/home/pete/wefwefwef/go/src/go.starlark.net/starlark/testdata/builtins.star:27:10: in <toplevel>
/home/pete/wefwefwef/go/src/go.starlark.net/starlarktest/assert.star:14:14: in _eq
Error: 1 != 2
starlarktest.go:117: Traceback (most recent call last):
/home/pete/wefwefwef/go/src/go.starlark.net/starlark/testdata/builtins.star:37:11: in <toplevel>
/home/pete/wefwefwef/go/src/go.starlark.net/starlark/testdata/builtins.star:35:11: in abs_bigint
/home/pete/wefwefwef/go/src/go.starlark.net/starlarktest/assert.star:14:14: in _eq
Error: 264140488580 != -264140488581
FAIL
```
> rename math.abs to math.fabs (fixes #362) and introduce `Universe["abs"]`

- starlark/int.go
- starlark/testdata/float.star
- starlarktest/starlarktest.go
Fixes https://github.com/google/starlark-go/issues/375
> fix overflow bug in finiteFloatToInt

- starlark/int.go
- starlark/value.go
Instead of `math.NextAfter`, use a strict `<`.
Fixes #375
> float: a cleaner fix to issue #375

- starlark/int_generic.go
- starlark/int_posix64.go
This PR disables the int32 optimization on openbsd because its default ulimit is only about 1GB.
Fixes #382
[Note: comments by reviewers refer to PR's description of original approach, which was abandoned, as explained in the code comment.]
> starlark: disable int32 optimization on openbsd

- .github/workflows/tests.yml
- internal/test.sh
It runs all tests and confirms go.mod and go.sum are tidy, just like
the Travis CI test.
The action runs with Go 1.16 and 1.17 on darwin, linux, and windows.
> Add GitHub action for testing

- internal/chunkedfile/chunkedfile.go
- internal/test.sh
- starlarktest/assert.go
- starlarktest/starlarktest.go
The previous implementation of DataFile (which abstracts different build systems' ways of locating test data files) constructed file names of data files using $GOPATH; also, it used a cross-package reference to locate the assert.star file. This doesn't work under Go modules. Now, DataFile looks only in the current directory, and the assert.star file is moved into a constant section of the executable.
Also, fix tests historically broken on Mac/Windows due to diff and CR LF differences.
> avoid cross-package references in tests

- doc/spec.md
This fixes the link to the Bazel's build language.
> Fix broken link to Bazel's build language

- doc/spec.md
This fixes the link to the Java implementation of Starlark in spec.md.
> Fix the link to the Java implementation

- starlark/value.go
Fixes https://github.com/google/starlark-go/issues/360
> Expose CompareLimit variable, controlling recursion when comparing cyclic data.

- starlark/testdata/function.star
- starlark/unpack.go
Users of tools such as Bazel and ours arguably edit mostly
the kwargs of functions the tool provides. Typos often slip
through and spelling suggestion can save some headache.
This change may affect the message string of some errors.
Signed-off-by: Pierre Fenoll <pierrefenoll@gmail.com>
> Suggest keyword argument based on spelling in UnpackArgs

- doc/spec.md
- starlark/library.go
- starlark/testdata/string.star
See https://github.com/bazelbuild/starlark/pull/212 for spec change
See https://github.com/bazelbuild/bazel/pull/14824 for Java PR
See https://github.com/facebookexperimental/starlark-rust/commit/7a7ef4b61afd375e832ee0f5cac1ddd38cc349d5 for Rust commit
Updates https://github.com/bazelbuild/starlark/issues/185
> Add strings.remove{pre,suf}fix methods

- starlark/testdata/benchmark.star
- starlark/value.go
Drops Items() range in favour of looking through the hashtable list
directly. This avoids an allocation, added a benchmark to verify.
Old:
Benchmark/bench_dict_equal-4               18782             61652 ns/op           57344 B/op          2 allocs/op
New:
Benchmark/bench_dict_equal-4               29802             39585 ns/op               0 B/op          0 allocs/op
> starlark: remove allocs on Dict ranges for dictsEqual and write

- doc/spec.md
- starlarkjson/json.go
- syntax/scan_test.go
Sorry for a pedantic PR. I'm just tired of looking at messages from an overly zealous spell checking tool every time I try to pull an update into our source tree.
> Fix some typos.

- starlark/eval.go
- starlark/interp.go
This hook gives someone the ability to intercept and potentially
change the behavior when maxSteps is reached. The default behavior
of canceling is preserved.
> Add a OnMaxSteps optional handler to Thread (#410)

- README.md
Reference: https://golang.org/doc/go-get-install-deprecation
I’m unable to run the REPL by following the build instructions in the `README.md`, but using `go install` instead of `go get` works for me:
```console
$ podman run --pull always -it --rm docker.io/library/golang:latest
root@445c025009b7:/go# go version
go version go1.18.4 linux/amd64
root@445c025009b7:/go# starlark
bash: starlark: command not found
root@445c025009b7:/go# go get -u go.starlark.net/cmd/starlark
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' …
```
> Fix build instructions for Go 1.18+

- .github/workflows/tests.yml
- go.mod
- go.sum
- starlark/bench_test.go
- starlark/int.go
- starlark/int_generic.go
- starlark/int_posix64.go
- starlark/int_test.go
The Int optimization uses a 4GB virtual address allocation to represent
32-bit values as addresses to avoid allocation. However, some environments
have limited address space.
This change permits the mmap to fail, and in that case it prints a warning
and falls back to always allocating a big.Int, even for small numbers.
Each access to an Int must check the smallints global to see whether the
optimization is active.  The extra dynamic check doesn't cost much:
```
$ go test -run=nope -bench=BenchmarkStarlark -count=3 ./starlark    # > before, after
$ go install golang.org/x/perf/cmd/benchstat@latest
$ ~/go/bin/benchstat  before after
name                                  old time/op  new time/op   delta
Starlark/bench_bigint-16               206µs ± 0%    212µs ± 0%   ~     (p=0.100 n=3+3) …
```
> starlark: fall back to slow Ints if mmap fails

- doc/spec.md
- internal/compile/compile.go
- starlark/eval.go
- starlark/hashtable.go
- starlark/interp.go
- starlark/testdata/dict.star
- starlark/value.go
This change adds support for the `x | y` operation (ordered union) in dictionaries and the in-place `x |= y` statement, in which the resulting value of x aliases the original, which is mutated.
Spec change:  https://github.com/bazelbuild/starlark/pull/215
Java change: https://github.com/bazelbuild/bazel/pull/14540
> Add dict|dict and dict|=dict

- doc/spec.md
Changed items:
1. The section `Module execution` has the same level as `Statements`, both has the prefix "##", but it's just a sub item under `Statements`. It seems not correct. So increased `Module execution` to +1 level.
2. `#name-resolution` is a wrong link, so replaced it with `#built-in-constants-and-functions`.
3. The lambda example has wrong output, corrected.
4. typo, `element` --> `tuple`
There might be another error in https://github.com/google/starlark-go/blob/master/doc/spec.md#lists , I am not quite sure about it and don't know how to update it. See below,
```
For most types, x += y is equivalent to x = x + y, except that it evaluates x only once, that is, it allocates a new list to hold the concatenation of x and y. However, if x refers to a list, the statement does not …
```
> Update spec.md to correct some mistakes

- starlark/eval.go
- starlark/eval_test.go
- starlark/interp.go
Imlemented ResetStepsAndCancelReason() and a test
This ResetStepsAndCancelReason() is very helpful for limiting cpu usage per Call or CallInternal
> Imlemented ResetStepsAndCancelReason()

- starlark/eval.go
- starlark/eval_test.go
- starlark/hashtable.go
- starlark/interp.go
This change uses defer for the cleanup logic in in Call and
Function.CallInternal so that panics originating in application
functions called by the interpreter can safely pass through
the interpreter without leaving the thread in a bad state
(e.g. frames still on the stack).
This seems to have an impact of ~0.7% on the 'calling' benchmark,
which represents the worst possible case.
Also, a test.
Fixes #419
> starlark: use defer for cleanup so that panics pass through safely

- lib/json/json.go
- starlark/testdata/json.star
Also, use uppercase for "JSON" in the same error message.
> lib/json: fix trivially broken tests

- starlark/int.go
Hi, I am submitting a patch that is the result of a memory problem I am investigating.
ATM I cannot share the code that is having the problem, but I could isolate it in a separate program:
```golang
package main
import (
"flag"
"fmt"
"math/big"
"os"
"runtime"
"runtime/pprof"
"time"
"go.starlark.net/starlark"
)
var asd starlark.Float
var (
testcase = flag.Int("testcase", 0, "testcase")
)
func main() {
flag.Parse()
f, _ := os.Create("profile")
result := make([]starlark.Value, 0, 1024*1024*10)
defer func() {
runtime.GC()
pprof.Lookup("heap").WriteTo(f, 0)
f.Close()
runtime.KeepAlive(result)
}()
var integer starlark.Int
fmt.Printf("Testcase %d\n", *testcase)
switch *testcase {
case 0:
// Small integer
integer = starlark.MakeInt64(1 << 16)
case 1:
// Big integer (>100 bits)
integer = …
```
> Fixing bad allocation pattern in `float` builtin

- lib/proto/proto.go
- starlark/eval_test.go
- starlark/testdata/proto.star
Consider the following Stralark line:
msg.repeated = [1,2,3]
Without this commit, that line appends three elements to the previous existing repeated values. With this commit, that line replaces the previous repeated values with new three items.
I believe the old semantics is simply a bug, and that most users would expect an assignment to overwrite the previous value.
> lib/proto: Allow replacing repeated fields, instead of appending.

- lib/time/time.go
- starlark/testdata/time.star
I know that the truthiness of timestamps isn't well defined, but the current behaviour is the opposite of what I would expect:
```
Welcome to Starlark (go.starlark.net)
>>> bool(time.now())
False
>>> bool(time.parse_time("0001-01-01T00:00:00Z"))
True
```
This change inverts the existing logic so that any time other than `0001-01-01T00:00:00Z` will evaluate to True.
Alternatively, I think that considering all times to be `True` would also be acceptable. Thoughts?
> lib/time: consider any Time other than zero instant to be truthy

- starlark/int_test.go
This change matters only in google3/blaze.
Within google3/blaze, all Go tests have additional initialization logic added by the build system. That causes the flags to be parsed before TestMain runs, resulting in a "flag provided but not defined" error when the test spawns itself from a subshell. Moving the flag definition to package-level variable is enough to fix the initialization order.
> int_test: Move `--entry` flag definition from TestMain to package init.

- starlark/unpack.go
Using MethodByName disables deadcode elimination in the linker (see the
deadcode function in $GOROOT/src/cmd/link/internal/ld/deadcode.go).
Since the only use of MethodByName is with a static string as an
argument it can be easily replaced with a downcast to an interface.
> starlark: do not use reflect.Value.MethodByName

- starlarkstruct/struct.go
Fixes https://github.com/google/starlark-go/issues/448
> Struct.String() does not quote starlark.String custom constructor

- starlark/profile_test.go
Previously, the test would compute the first 100,000 elements of the Fibonacci sequence, holding them all in an array. Since elements may have over 20,000 digits, this allocates a lot of memory, which, under tight ulimits of virtual address space, in conjunction with the mmap int optimization, may cause the process to have insufficient virtual address space to allocate the necessary memory.
This change causes it to compute but not retain the elements of the sequence.
Fixes google/starlark-go#455
> starlark: optimize TestProfile

- starlark/eval.go
- starlark/hashtable.go
- starlark/testdata/benchmark.star
- starlark/value.go
Removes allocations on Set operations. Added a single benchmark testing
equality, should improve other set operations too.
Old:
Benchmark/bench_set_equal-8                35050             34043 ns/op           16384 B/op          1 allocs/op
New:
Benchmark/bench_set_equal-8                41312             28884 ns/op               0 B/op          0 allocs/op
> starlark: set internal iteration use hashtable linked lists

- resolve/resolve.go
- resolve/testdata/resolve.star
I had a duplicate kwargs named 'disabled'. This
ended up with a message 'keyword argument disabled repeated', which is really difficult to parse.
Hope to clarify things by changing that text a bit.
> Disambiguate a resolve message

- lib/time/time.go
- starlark/int.go
- starlark/value.go
Re: https://github.com/google/starlark-go/issues/356
This adds a new `TotallyOrdered` interface, similar to `Comparable` which returns an integer representing the <, ==, > relation between values. The `CompareDepth` function has been to updated check for this interface and handle this return style if applicable.
Also refactors `int`, `float`, `time.Time` and `time.Duration` types to use the new interface.
The previous `Comparable` interface will have to be maintained, not just for API compatibility but also for types which define equality/inequality but not ordering (for example, [structs](https://github.com/google/starlark-go/blob/c52844e64a10fb0a67ae99619ee98a49de4f8210/starlarkstruct/struct.go#L247))
- Is the ThreeWayCompareSameType name too verbose? I was thinking about overloading …
> Adding new ThreeWayComparable interface

- starlark/hashtable.go
**Update:** Decided that this is not a worthwhile optimization due to modest performance improvements, updating the TODO and otherwise not making any other changes. Leaving my original notes for reference.
--------
Addressing this TODO I found in the hashtable implementation because it seems like a clear performance win and an interesting investigation.
tl;dr instead of using the `hashtable.insert` method to copy elements into the new bucket, we can write a specialized `hashtable.growInsert` method which bypasses some of the deduplication and checks which only apply when inserting into a  pre-existing hashtable.
Optimizations include:
- Re-using the already computed hash of key, rather than recomputing
- Not looking for existing keys while inserting, deduplication is done at initial …
> Optimizing hashtable.grow() for faster hashtables

- lib/json/json.go
- starlark/testdata/json.star
This is the starlark-go counterpart to bazelbuild/bazel@71fb1e4
It is useful to be able to decode a potentially invalid JSON string without
failing Starlark evaluation. Typically, in this case, we would want to return
a default value - either a reasonable safe default or some domain-specific
representation of "we encountered an error".
Note that the original behavior of json.decode failing on invalid JSON input
still remains (for lack of a better word) the default: the `default` value,
even if it is `None`, must be specified explicitly.
Fixes #465
> Allow json.decode to return a default value if decoding fails

- lib/json/json.go
> lib/json: fix go1.17 build by avoiding reflect.Value.UnsafePointer

- starlark/int_test.go
Test breaks in some environments where pre-existing allocations exceed 1Gb.
> Bump memory boundary to 4Gb in test

- starlarkjson/json.go
Hi,
I experienced a problem in which the go-list command couldn't find go.starlark.net/stalarkjson when making the Debian package of starlark-go.
The root cause is the typo in the [import comments](https://pkg.go.dev/cmd/go#hdr-Import_path_checking) of starlarkjson/json.go file caused by #367. This typo makes the go-list command under GO111MODULE=off to give up finding go files of starlark-go. As a result, the packaging in Debian failed.
Would you please accept the PR to fix that typo?
> Fix typo in import comment of json.go

- starlark/int_generic.go
- starlark/int_posix64.go
According to the [documentation](https://pkg.go.dev/cmd/go#hdr-Build_constraints), ppc64x is not a valid flag, making `TestIntFallback` fail. s390x is also missing and it works fine.
```
--- FAIL: TestIntFallback (0.01s)
int_test.go:130: expected warning was not printed. Output=<<>>
```
> Fix build flags for s390x, ppc64, and ppc64le

- starlarktest/assert.star
- starlarktest/starlarktest.go
> starlarktest/assert.star: allow +/-1 ULP in float eq comparisons

- lib/proto/proto.go
With this change, it becomes possible to instantiate `map<k,v>` type fields in Protobuf messages from Starlark.
Maps can be constructed from any Starlark type that implements starlark.IterableMapping.
Protobuf messages can have most types as keys/values, so the type conformity is checked individually for each key/value pair (as the Starlark side of things is dynamically typed).
This has been tested against fairly complex proto messages containing maps.
Map operations apart from construction are not supported in this CL.
> lib/proto: add support for instantiating proto map fields

- syntax/testdata/scan.star
This will change the output directory from `blaze-genfiles` to `blaze-bin`
> Replace `ctx.new_file` with `ctx.actions.declare_file`

- starlark/int.go
- starlark/value.go
Google's linter is complaining about the following:
* comment on exported method Int.Cmp should be of the form "Cmp ..."
* receiver name x should be consistent with previous receiver name i for Int
* exported method Float.Cmp should have comment or be unexported
* receiver name x should be consistent with previous receiver name f for Float
* method parameter y_ should be y
> trivial: Fix golint errors

- doc/spec.md
- resolve/binding.go
- starlark/value.go
- syntax/walk_test.go
This PR fixes typos in the Go comments and markdown docs.
> Fix typos in comments and docs

- internal/compile/codegen_test.go
- internal/compile/compile.go
- internal/compile/serial.go
- lib/proto/cmd/star2proto/star2proto.go
- repl/repl.go
- resolve/resolve.go
- resolve/resolve_test.go
- starlark/bench_test.go
- starlark/eval.go
- starlark/eval_test.go
- starlark/interp.go
- syntax/options.go
- syntax/parse.go
- syntax/syntax.go
This change eliminates the need for client applications to set global variables to control dialect options, as globals are error-prone and concurrency hostile.
All relevant API functions Foo now have a variant FooOptions that takes an explicit FileOptions; the original function accesses the legacy options by reading the global variables.
Fixes #435
> syntax: parameterize API over FileOptions, avoid globals

- doc/spec.md
- starlark/eval.go
- starlark/library.go
- starlark/testdata/builtins.star
- starlark/testdata/int.star
- starlark/testdata/set.star
- starlark/value.go
This PR enables the following operations:
- `S.difference(x)` AKA `S - x`
- `S.intersection(x)` AKA `S & x`
- `S.symmetric_difference(x)` AKA `S ^ x`
- `S.issubset(x)` AKA `S <= x` or `s < x`
- `S.issuperset(x)` AKA `S >= x` or `S > x`
I also unified the unified the implementations of these operations which were inlined in the evaluator with the implementation defined in `values.go`, to reduce duplication.
Demo:
```
Welcome to Starlark (go.starlark.net)
>>> x = set([1,2,3])
>>> y = set([3,4,5])
>>> x.intersection(y)
set([3])
>>> x.difference(y)
set([1, 2])
>>> x.symmetric_difference(y)
set([1, 2, 4, 5])
>>> x.issuperset(y)
False
>>> x.issuperset(set([1,2]))
True
>>> x.issubset(y)
False
>>> x.issubset(set([1,2,3,4]))
True
```
> Adding additional set builtins

- .github/workflows/tests.yml
- go.mod
- go.sum
- starlark/int_generic.go
- starlark/int_posix64.go
This PR changes the minimum supported version of Go to 1.18 by modifying `go.mod` file.
Other changes:
- added `1.20` and `1.21` Go versions to GitHub actions file;
- fixed build tags by running `go fix ./...`;
- updated GitHub actions.
See https://github.com/google/starlark-go#stability.
> Change mod file to use Go 1.18; extend ci test versions

- starlark/eval_test.go
> Refactor TestLoadBacktrace to use errors.Unwrap

- resolve/resolve.go
- resolve/resolve_test.go
- resolve/testdata/resolve.star
- starlark/eval_test.go
- starlark/testdata/recursion.star
- starlark/testdata/while.star
The new struct `FileOptions` allows for fine grained control over language feature.
However, it didn't respect `FileOptions.TopLevelControl` flag, as the only way to actually allow if/for/while in the top level context was to enable `FileOptions.GlobalReassign` flag.
> Make resolve follow FileOptions.TopLevelControl

- starlark/int.go
This PR adds a fast path for very big int to float conversion that always get converted to `±Inf`.
> Limit CPU and memory usage for int-to-float conversion

- lib/time/time.go
- lib/time/time_test.go
Closes https://github.com/google/starlark-go/issues/516.
p.s. there are quite a few changes that go fmt wants to make. I kept them out of this PR.
> time: per-thread time.now() function

- doc/spec.md
- starlark/eval.go
- starlark/library.go
- starlark/testdata/string.star
When no conversions are specified, interpolation over an empty tuple is accepted, but interpolation over an empty dict is rejected:
```
>>> 'foo' % ()
"foo"
>>> 'foo' % {}
Traceback (most recent call last):
<stdin>:1:7: in <expr>
Error: too many arguments for format string
```
For context, extra dict arguments are not rejected when a conversion is present:
```
>>> '%(a)d' % {'a': 1, 'unused': 2}
"1"
```
This PR relaxes the 'too many arguments' check for mappings and adds tests to ensure consistency between tuples and dicts
> Remove 'too many arguments' error when interpolating over mappings

- lib/time/time.go
`Time.String()` states in the documentation that it formats time according to the string `2006-01-02 15:04:05.999999999 -0700 MST`, however it uses `time.Time.String()` methods which, if available, adds to that string the monotonic clock, leading to inconsistent output. For example:
```
>>> time.now()
2024-01-23 14:47:50.352396992 +0100 CET m=+210.079650729
>>> time.parse_time("2024-01-23T14:47:50.352396992+01:00")
2024-01-23 14:47:50.352396992 +0100 CET
```
This PR uses a format string instead, so that the output does never contain the monotonic clock.
> Remove debug clock from Time.String()

- .github/workflows/tests.yml
- go.mod
- starlark/hashtable.go
Also, use go1.19's maphash.String.
The benchmark supports continuing to use FNV for short strings.
> starlark: update go.mod to drop go1.18 support

- starlark/hashtable.go
- starlark/iterator_test.go
- starlark/value.go
starlark: new API for go1.23 push iterators
This change defines two helpers, Elements(seq)
and Entries(mapping), that adapt the Iterable and
IterableMapping interfaces to one- and two-variable
go1.23 range loops. The new syntax is more concise
and frees the caller from worrying about Iterator.Done.
We do not yet update any calls to use them, so that
the project can continue to be build with pre-go1.23
releases of Go.
Also, define Elements methods on {*List,Tuple,*Set}
and an Entries method on *Dict. These optimized iterators
(which can fetch both k and v in one go) will be
used by the Elements and Entries standalone functions
when the operand supports it. (User-defined types
can implement these methods too, although the
interface isn't currently documented.)
Also, a go1.23-only test of …
> starlark: new API for go1.23 push iterators

- syntax/parse.go
- syntax/testdata/errors.star
syntax: report start-of-token pos for parsePrimary errors
(Conceivably other places need a similar ttreament, but they all seemed benign or marginal.)
Fixes #532
> syntax: report start-of-token pos for parsePrimary errors

- starlark/iterator_test.go
- starlark/value.go
According to https://github.com/golang/go/issues/66626#issuecomment-2035188011, the convention for iterator methods is that they should return an iterator, not be an iterator. The caller thus uses this form:
for _ elem := range v.Elements() { ... }
not this one:
for _ elem := range v.Elements { ... }
This is unfortunately a breaking API change, but since go1.23 is not yet released, no-one should be using the new range syntax yet.
> starlark: eta-abstract the new iterators

- internal/compile/compile.go
- internal/compile/serial.go
- starlark/debug.go
- starlark/eval_test.go
- starlark/interp.go
- starlark/value.go
This change adds the following new API to allow debugging tools and built-in functions access to the internals of Function values and call frames:
package starlark
type Binding struct {
Name string
Pos  syntax.Position
}
func (fr *frame) NumLocals() int
func (fr *frame) Local(i int) (Binding, Value)
type DebugFrame interface {
...
NumLocals() int
Local(i int) (Binding, Value)
}
func (fn *Function) NumFreeVars() int
func (fn *Function) FreeVar(i int) (Binding, Value)
This is strictly a breaking change, but the changed functions (the Local methods) were previously documented as experimental. The fix is straightforward.
Also, a test of DebugFrame to write an 'env' function in a similar vein to Python's 'dir' function.
Fixes #538
> starlark: add debug API for Locals and FreeVars

- starlark/eval_test.go
- starlark/unpack.go
Fixes https://github.com/google/starlark-go/issues/544
> starlark: tweak how UnpackArgs enforces optional args

- repl/repl.go
- resolve/resolve.go
- starlark/eval.go
- syntax/parse.go
This PR adds a newline before the `"// Deprecated:"` comments to fix the display of deprecated functions on the [pkgsite](https://pkg.go.dev/go.starlark.net). The changes are made in accordance with the guidelines on the wiki page https://go.dev/wiki/Deprecated.
Before:
[<img width="1122" alt="image" src="https://github.com/google/starlark-go/assets/3228886/6e26f963-5d83-4c03-b0b0-45ccbb8d35f7">](https://pkg.go.dev/go.starlark.net/starlark#Eval)
After:
> starlark,syntax,repl: improve docs for deprecated functions

- doc/spec.md
- starlark/profile.go
- starlark/value.go
- syntax/parse.go
The PR corrects grammar mistakes and removes duplicated words in doc comments.
> docs: fix typos

- starlark/iter.go
- starlark/value.go
- syntax/options.go
The correct type for new iterators is iter.Seq, which depends on a go1.23-only package, so we must limit the new functions to new toolchains.
In principle this is (yet another) breaking change, but I suspect only users of (pre-)go1.23 will notice, and they are living on the bleeding edge by choice. (Even then, if the iterators are used only as `range` operands, they will be fine.)
Also, fix a couple of doc links.
> starlark: require go1.23 for new iterators

- starlark/profile.go
Updates #546
Updates golang/go#67401
> starlark: profiler: stop using runtime.nanotime via linkname hack

- starlark/eval.go
The current overflow check for repeat operation fails to check when a multiplication wraps to a positive number.
On 64 bits build it is hard to get one (as you would need a tuple/string with more than 2^32 element - but it's still possible).
On a 32 bits build however it is quite trivial:
```python
len((1,) * 641 * 6700417) # returns 1
len([1] * 641 * 6700417) # returns 1
"a" * 641 * 6700417
```
This PR uses `bits.Mul` to make sure that this does not happen.
> Fix overflow checking for repeat operation

- syntax/parse.go
This appears to be dead code, as we have just checked for RPAREN previously
> Removed dead code for RPAREN.

- lib/json/json.go
- starlark/testdata/json.star
The previous code carelessly used Go's %g operator when it should have used Starlark's.
Fixes #563
> lib/json: encode floating point numbers with a decimal point

- starlark/value.go
- starlarkstruct/struct.go
- starlarkstruct/testdata/struct.star
The Freeze method needs to check for a `frozen` condition just like all the other types of values, otherwise there can be infinite recursion.
The test that I'm adding here would crash without the fix.
* Fixes #566
> Don't crash when freezing a struct with a circular reference

- repl/repl.go
This Pull Request implements the feature request to support the `_` special variable in REPL mode, which stores the value of the last evaluated expression. This enhancement aligns the Starlark REPL behavior more closely with Python's REPL, improving the interactive experience for users. Fixed issue #569.
**Changes Made:**
- In `repl.go`, after each successful expression evaluation, the result is stored in the `_` variable within the `globals` dictionary.
- The `_` variable is only updated when an expression is evaluated, not after executing statements.
- If an error occurs during expression evaluation, the `_` variable remains unchanged.
- No changes are made to script execution outside of REPL mode.
**Benefits:**
- Improves interactive debugging and experimentation workflow.
- Provides …
> Add support for "_" special variable in REPL mode to store last expression value

- doc/spec.md
- starlark/library.go
- starlark/testdata/builtins.star
- starlark/testdata/set.star
- starlark/value.go
The method [update](https://github.com/bazelbuild/starlark/blob/master/spec.md#setupdate) on the type `set` is available in the Bazel implementation of Starlark, but unfortunately not this Go implementation. This PR will augment the `set` implementation to also support the `update` method.
> Implement set.update method

- doc/spec.md
- starlark/library.go
- starlark/testdata/set.star
The `union` function on `set` is inconsistent with the behaviour of `update` as it does not support multiple iterable positional arguments as is the case in the Bazel specification of the language. This PR will align `starlark-go` with the Bazel spec.
Note that the `set.union` method no longer uses the `Union` function defined in `value.go` in order to avoid making a new `set` instance for each interable processed.
> correct set.union method

- internal/compile/compile.go
- internal/compile/serial.go
- starlark/eval.go
- starlark/testdata/benchmark.star
This eliminates the linear scan over locals in the interpreter when processing named arguments. This reduces the new benchmark from 1081ns to 843ns (-22%).
(This was inspired by recent work in the Java-based implementation, but findParams seemed to be a bigger hit in that case, possibly because of the two extra levels of indirection involved in the length comparison (hot path) of a Java array of Java strings, versus Go where they are all in the same cache line.)
> internal/compile: build index of local vars

- doc/spec.md
- starlark/library.go
- starlark/testdata/set.star
Match language spec: https://github.com/bazelbuild/starlark/blob/master/spec.md#set%C2%B7add
Working towards https://github.com/google/starlark-go/issues/584
> Never allow set.add() / set.discard() if set is frozen or being iterated

- starlark/unpack.go
This PR turns `unpackOneArg` into an exported function.
The intended use case is leveraging the unpacking logic in custom `Unpacker` implementations (e.g., unpacking into a `string`-based enum with validation by first unpacking into a `*string` using the default logic, then validating the value before converting to a typed enum). Without this, one would either have to re-implement the relevant parts of the `unpackOneArg` logic, or use the workaround of `UnpackPositionalArgs("", starlark.Tuple{arg}, nil, 1, target)` and then stripping the `": for parameter 1: "` prefix of any error returned (which obviously is ugly).
> Export UnpackOneArg

- syntax/parse.go
- syntax/scan.go
If an illegal token (typically a Python keyword that isn't supported in Starlark) is encountered, the parser prints it as just `illegal token` in the error message. Without looking at the precise line:col position, this can be very confusing, especially for people coming from a Python background that are new to Starlark.
This PR ensures that in the illegal token case, the token value is printed alongside the `illegal token` string.
Before:
```
print(None is None)  # <script>:1:14: got illegal token, want ','
```
After:
```
print(None is None)  # <script>:1:14: got illegal token "is", want ','
```
> Print token value for illegal tokens

- lib/proto/proto.go
- starlark/testdata/proto.star
- starlark/testdata/proto/test.fds
- starlark/testdata/proto/test.proto
This encodes the existing behaviour.
It adds a fix to `has()`.
> proto: add tests for extensions

- starlark/value.go
Pass a pointer to Value to Next() in the docs. Only relevant for older Go versions but still worth fixing.
> Update Iterator comment for correct usage
